export interface CheatCode {
  id: string;
  name: string;
  description: string;
  category: string;
  codePS5: string;
  codeXbox: string;
  codePC: string;
  effect: string;
}

export const cheatCategories = [
  { id: "all", label: "Tous" },
  { id: "sante", label: "Sante & Armure" },
  { id: "armes", label: "Armes" },
  { id: "vehicules", label: "Vehicules" },
  { id: "police", label: "Police" },
  { id: "meteo", label: "Meteo" },
  { id: "gameplay", label: "Gameplay" },
];

export const cheatCodes: CheatCode[] = [
  // Sante & Armure
  {
    id: "full-health",
    name: "Sante Max",
    description: "Remet la barre de sante a 100%",
    category: "sante",
    codePS5: "X X L1 R1 Triangle Rectangle",
    codeXbox: "A A LB RB Y X",
    codePC: "HEALME",
    effect: "Sante restauree",
  },
  {
    id: "full-armor",
    name: "Armure Max",
    description: "Donne une armure complete",
    category: "sante",
    codePS5: "R1 R1 L1 Rectangle Triangle L1",
    codeXbox: "RB RB LB X Y LB",
    codePC: "ARMORUP",
    effect: "Armure complete",
  },
  {
    id: "invincible",
    name: "Invincibilite",
    description: "Devient invincible pendant 5 minutes",
    category: "sante",
    codePS5: "Rectangle Rectangle L1 R1 R2 Triangle Rectangle Triangle",
    codeXbox: "X X LB RB RT Y X Y",
    codePC: "GODMODE",
    effect: "Invincibilite 5 min",
  },
  // Armes
  {
    id: "weapons-tier1",
    name: "Armes Niveau 1",
    description: "Obtient les armes de base (pistolet, batte, shotgun)",
    category: "armes",
    codePS5: "Triangle Rectangle R1 L1 R2 R2",
    codeXbox: "Y X RB LB RT RT",
    codePC: "TOOLUP1",
    effect: "Armes basiques",
  },
  {
    id: "weapons-tier2",
    name: "Armes Niveau 2",
    description: "Obtient les armes intermediaires (SMG, fusil assault, sniper)",
    category: "armes",
    codePS5: "Triangle R1 R1 L1 R2 Rectangle L1 R1",
    codeXbox: "Y RB RB LB RT X LB RB",
    codePC: "TOOLUP2",
    effect: "Armes intermediaires",
  },
  {
    id: "weapons-tier3",
    name: "Armes Niveau 3",
    description: "Obtient les armes lourdes (lance-roquettes, minigun, C4)",
    category: "armes",
    codePS5: "R1 R2 L1 R2 L2 R1 L1 R2 R2",
    codeXbox: "RB RT LB RT LT RB LB RT RT",
    codePC: "TOOLUP3",
    effect: "Armes lourdes",
  },
  {
    id: "explosive-melee",
    name: "Coups explosifs",
    description: "Les coups de poing et de pied deviennent explosifs",
    category: "armes",
    codePS5: "Rectangle R2 L1 R2 L2 R1 R2 L2",
    codeXbox: "X RT LB RT LT RB RT LT",
    codePC: "HOTHANDS",
    effect: "Coups explosifs",
  },
  // Vehicules
  {
    id: "spawn-infernus",
    name: "Infernus",
    description: "Fait apparaitre la supercar Infernus",
    category: "vehicules",
    codePS5: "R2 L2 L1 R2 R1 L2 Rectangle L1",
    codeXbox: "RT LT LB RT RB LT X LB",
    codePC: "RAPIDGT",
    effect: "Infernus apparait",
  },
  {
    id: "spawn-cheetah",
    name: "Cheetah",
    description: "Fait apparaitre la sportive Cheetah",
    category: "vehicules",
    codePS5: "R2 R1 L2 L1 L2 L1 R2 R2",
    codeXbox: "RT RB LT LB LT LB RT RT",
    codePC: "COMETME",
    effect: "Cheetah apparait",
  },
  {
    id: "spawn-helicopter",
    name: "Helicoptere",
    description: "Fait apparaitre un helicoptere",
    category: "vehicules",
    codePS5: "R2 R2 L2 R2 L2 L2 R2 L1",
    codeXbox: "RT RT LT RT LT LT RT LB",
    codePC: "FLYHIGH",
    effect: "Helicoptere apparait",
  },
  {
    id: "spawn-boat",
    name: "Bateau rapide",
    description: "Fait apparaitre un speedboat",
    category: "vehicules",
    codePS5: "R1 L1 R2 L1 L2 R2 R2 L1",
    codeXbox: "RB LB RT LB LT RT RT LB",
    codePC: "SEASICK",
    effect: "Speedboat apparait",
  },
  {
    id: "moon-gravity",
    name: "Gravite lunaire",
    description: "Reduit la gravite (sauts plus hauts, vehicules legers)",
    category: "vehicules",
    codePS5: "L2 R2 L1 R2 L2 L2 R1 R2",
    codeXbox: "LT RT LB RT LT LT RB RT",
    codePC: "FLOATAWAY",
    effect: "Gravite reduite",
  },
  // Police
  {
    id: "wanted-up",
    name: "Rechercher +1",
    description: "Augmente le niveau de recherche de 1 etoile",
    category: "police",
    codePS5: "R1 R1 L1 R2 L1 R2 R1 L1",
    codeXbox: "RB RB LB RT LB RT RB LB",
    codePC: "WANTEDUP",
    effect: "Recherche +1 etoile",
  },
  {
    id: "wanted-down",
    name: "Rechercher -1",
    description: "Reduit le niveau de recherche de 1 etoile",
    category: "police",
    codePS5: "R1 R1 L1 R2 L1 L2 R1 L1",
    codeXbox: "RB RB LB RT LB LT RB LB",
    codePC: "LAWLESS",
    effect: "Recherche -1 etoile",
  },
  {
    id: "wanted-clear",
    name: "Effacer recherche",
    description: "Supprime toutes les etoiles de recherche",
    category: "police",
    codePS5: "R1 R1 L1 L2 R2 R2 L1 R2",
    codeXbox: "RB RB LB LT RT RT LB RT",
    codePC: "COPOFF",
    effect: "Recherche effacee",
  },
  // Meteo
  {
    id: "weather-sunny",
    name: "Temps ensoleille",
    description: "Change la meteo pour un ciel degage",
    category: "meteo",
    codePS5: "R2 X L1 L1 L2 L2 X R2",
    codeXbox: "RT A LB LB LT LT A RT",
    codePC: "CLEARSKY",
    effect: "Temps ensoleille",
  },
  {
    id: "weather-rain",
    name: "Temps pluvieux",
    description: "Declenche la pluie",
    category: "meteo",
    codePS5: "R2 X L1 L1 L2 L2 Triangle R2",
    codeXbox: "RT A LB LB LT LT Y RT",
    codePC: "RAINDANCE",
    effect: "Pluie",
  },
  {
    id: "weather-thunder",
    name: "Orage",
    description: "Declenche un orage avec eclairs",
    category: "meteo",
    codePS5: "R2 X L1 L1 L2 L2 Rectangle R2",
    codeXbox: "RT A LB LB LT LT X RT",
    codePC: "STORMY",
    effect: "Orage",
  },
  // Gameplay
  {
    id: "slowmo",
    name: "Ralenti",
    description: "Active le mode ralenti (3x plus lent)",
    category: "gameplay",
    codePS5: "Triangle L1 L2 R2 Rectangle L1 R1 Triangle",
    codeXbox: "Y LB LT RT X LB RB Y",
    codePC: "SLOWTIME",
    effect: "Ralenti",
  },
  {
    id: "super-jump",
    name: "Super saut",
    description: "Saute beaucoup plus haut que la normale",
    category: "gameplay",
    codePS5: "L2 L2 R2 R2 Rectangle Triangle Rectangle L2",
    codeXbox: "LT LT RT RT X Y X LT",
    codePC: "HOPPY",
    effect: "Super saut",
  },
  {
    id: "drunk-mode",
    name: "Mode bourre",
    description: "Active le mode ivresse (commandes inversees)",
    category: "gameplay",
    codePS5: "Triangle R2 L2 R2 L1 R2 L2 Triangle",
    codeXbox: "Y RT LT RT LB RT LT Y",
    codePC: "LIQUORUP",
    effect: "Mode ivresse",
  },
  {
    id: "fast-run",
    name: "Course rapide",
    description: "Augmente la vitesse de course de 2x",
    category: "gameplay",
    codePS5: "Triangle L1 R1 L2 R1 Rectangle Triangle R2",
    codeXbox: "Y LB RB LT RB X Y RT",
    codePC: "CATCHME",
    effect: "Course 2x rapide",
  },
];